"""Add reset code columns

Revision ID: aaf5a85d9e2b
Revises: 4900c563b180
Create Date: 2026-07-01 13:31:07.038513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaf5a85d9e2b'
down_revision: Union[str, None] = '4900c563b180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_code_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_code_expires')
    op.drop_column('users', 'reset_code')
    # ### end Alembic commands ###
