"""Add vote field to issue_verifications

Revision ID: 4900c563b180
Revises: 8744053d267e
Create Date: 2026-06-24 20:13:20.664907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4900c563b180'
down_revision: Union[str, None] = '8744053d267e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    vote_enum = postgresql.ENUM('CONFIRM', 'FALSE_REPORT', 'ALREADY_FIXED', name='votetype')
    vote_enum.create(op.get_bind())
    op.add_column('issue_verifications', sa.Column('vote', sa.Enum('CONFIRM', 'FALSE_REPORT', 'ALREADY_FIXED', name='votetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_verifications', 'vote')
    vote_enum = postgresql.ENUM('CONFIRM', 'FALSE_REPORT', 'ALREADY_FIXED', name='votetype')
    vote_enum.drop(op.get_bind())
    # ### end Alembic commands ###
