"""add AI enrichment fields to issue

Revision ID: 8744053d267e
Revises: 13be90e79ca3
Create Date: 2026-06-24 19:59:52.603127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8744053d267e'
down_revision: Union[str, None] = '13be90e79ca3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('ai_category', sa.String(), nullable=True))
    op.add_column('issues', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('issues', sa.Column('severity', sa.Float(), nullable=True))
    op.add_column('issues', sa.Column('ai_reasoning', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'ai_reasoning')
    op.drop_column('issues', 'severity')
    op.drop_column('issues', 'ai_confidence')
    op.drop_column('issues', 'ai_category')
    # ### end Alembic commands ###
